Build one Docker image per Rust version and tag with cargo-chef version number (#71)
* Build one Docker image per Rust version and tag with cargo-chef version number

Fixes #58

* ci: Run docker pushes on each commit

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,4 +1,7 @@
 ARG BASE_IMAGE=rust
 FROM $BASE_IMAGE
 
-RUN cargo install cargo-chef && rm -rf $CARGO_HOME/registry/
+# Install musl-dev on Alpine to avoid error "ld: cannot find crti.o: No such file or directory"
+RUN ((cat /etc/os-release | grep ID | grep alpine) && apk add --no-cache musl-dev || true) \
+    && cargo install cargo-chef \
+    && rm -rf $CARGO_HOME/registry/
